name: Build
on:
  push:
    branches: [elfeat]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [label-slow]
    steps:
      - name: Update repository
        run: |
          if [ -d "/home/user/docker_site" ]; then
            cd /home/user/docker_site
            git checkout elfeat
            git pull origin main
          else
            cd /home/user
            git clone git@github.com:Deniska13113/html_pr.git
            git checkout elfeat
            mv html_pr docker_site
          fi
      - name: Restart containers
        run: |
          cd /home/user/docker_site
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker compose down  
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker compose up -d --build