name: Cicd
on:
  push:
    branches: [elfeat]
jobs:
  Copy:
    runs-on: label-slow
    steps:
      - name: Update repository
        run: |
          if [ -d "/home/user/docker_site" ]; then
            cd /home/user/docker_site
            git fetch origin
            git checkout elfeat
            git reset --hard origin/elfeat
            git clean -fd
          else
            cd /home/user
            git clone git@github.com:Deniska13113/html_pr.git
            mv html_pr docker_site
            cd /home/user/docker_site
            git checkout elfeat
          fi
  Test:
    needs: Copy
    runs-on: label-slow
    steps:
    - name: Test html
      run: |
        cd /home/user/docker_site/site_80/site
        htmlhint "**/*.html"
  Deploy:
    needs: Test
    runs-on: label-slow
    steps:
    - name: Restart containers
      run: |
        cd /home/user/docker_site
        echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker compose down  
        echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker compose up -d --build