name: Build
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [label-1, X64]
    steps:
      - name: Update repository
        run: |
          if [ -d "/home/user/docker_site" ]; then
            cd /home/user/docker_site
            git pull origin main
          else
            cd /home/user
            git clone git@github.com:Deniska13113/html_pr.git
            mv html_pr docker_site
          fi
      - name: Restart containers
        run: |
          cd /home/user/docker_site
          echo {{"secret.sudo_password"}} | sudo -Ss docker compose up -d  
          echo {{"secret.sudo_password"}} | sudo -Ss docker compose up -d --build